### ISSUE TITLE
Consider making SendClientMessage hooking optional

### ISSUE THREAD

**Issue by spacemud** [Open-GTO/zmessage#5]
In my gamemode I have quite a lot of wrapper functions that use `SendClientMessage`/`SendClientMessageToAll` that I use for various purposes, such as sending messages to a specific group of players. The problem with hooking `SendClientMessage` by default is that this message splitting has to be performed for each player that receives the message. This could probably be made more efficient by splitting the message just once and then sending the result to the group of players. As it's a bit more involved, an example could be added to the `README` to show how it's done.

So, my suggestions are:

1. Make an option for hooking the native message functions, like `ZMSG_HOOK_SENDCLIENTMESSAGE` or something. This could be on by default for backwards compatibility.
2. Remove the `static` modifier from the `ZMsg_ShiftStartPos`, `ZMsg_ShiftEndPos` and `ZMsg_MakeString` functions. This would let a scripter use these functions to split their own message and avoid unnecessary message splitting when looping.

**Comment by ziggi** [comment]
For what you need a `ZMsg_ShiftStartPos` and `ZMsg_ShiftEndPos` functions?

Also to achieve your goal you should make an array (like `array[10][ZMSG_MAX_CHAT_LENGTH + 1]`) and write all messages into it.

In this case I think what one special function will be more useful:
```Pawn
new
    array[10][ZMSG_MAX_CHAT_LENGTH + 1],
    messages;

messages = ZMsg_GetMessages(message, array);

for (...) { // players from your group
    for (new i = 0; i < messages; i++) {
        SendClientMessage(playerid, -1, array[i]);
    }
}
```
What you think about it?

**Comment by spacemud** [comment]
Yep, that seems like a much better solution - far easier to use.
